### ISSUE TITLE
[console] Incorrect link to the docs

### ISSUE THREAD

**Issue by babakfp** [hopinc/docs#26]
Hi

This may not be the right place to post this but I couldn't find the correct place.

Take a look at this video:

https://github.com/hopinc/docs/assets/44144724/93b81cda-a91e-42f3-ac27-2311882712cf

**Comment by looskie** [comment]
Hi, just fixed this.

I see the rest of your issues, would much prefer if you reported it in our [Discord](https://discord.gg/hop). But I do understand that we need a better process of reporting bugs within our client, as depending on people going to Discord is not a good solution.

Regardless, thank you for all your reports!
