### ISSUE TITLE
[console] Inconsistency in UI

### ISSUE THREAD

**Issue by babakfp** [hopinc/docs#27]
On the top right, it shows "B" (👍), and on the bottom left it shows "BFP".

![Screenshot 2023-10-05 081441](https://github.com/hopinc/docs/assets/44144724/70314a41-d7a9-427f-a2de-1e6c0a1dc9fc)

**Comment by looskie** [comment]
This is by design, Project's should have more characters to differentiate them from other projects. The top right is your username which doesn't need to be differentiated.
