### ISSUE TITLE
[console] Slider Componnet error not showing up when it's already dismissed...

### ISSUE THREAD

**Issue by babakfp** [hopinc/docs#30]
https://github.com/hopinc/docs/assets/44144724/efbf210c-beea-4d87-a4a1-3c7db10aff18

1. The max selectable value is `3`.
2. Select `3` (via keyboard).
3. Dismiss the error message by clicking away.
4. Focus on the Slider handle and try to increase the value again.
5. You will see it doesn't show the error anymore!
6. If you go to value `2` and go back to value `3` then you will see the error.

**Comment by looskie** [comment]
fixed
